language: c
services:
  - docker
before_install:
  - docker pull alexignatyev/optimer-deps:latest
  - docker run --env CXX=g++ -v Alexander-Ignatyev/optimer:/repo -itd --name build alexignatyev/optimer-deps
script:
  - docker exec build cmake -H/repo -B/build
  - docker exec build cmake --build /build
  - docker exec build cmake --build /build --target test
