language: c
services:
  - docker
before_install:
  - docker pull alexignatyev/optimer-deps:latest
  - docker run --env CXX=g++ -itd --name build alexignatyev/optimer-deps
  - docker exec build git clone https://github.com/Alexander-Ignatyev/optimer.git /repo
script:
  - docker exec build cmake -H/repo -B/build
  - docker exec build cmake --build /build
  - docker exec build cmake --build /build --target test
