section:
    name: main
    childs: 
        - property:
            name: branching_rule
            values: [3, 4]
            childs: 
                - property:
                    name: valuation_type
                    values: [serial]
                - property:
                    name: valueation_type
                    values: [parallel]
                    childs:
                        - section:
                            name: scheduler
                            childs:
                                - property:
                                    name: num_threads
                                    values: [2,4,6,8]
                                            